### ISSUE TITLE
FEYNMAN HIBBS LENNARD JONES

### ISSUE THREAD

**Issue by shaochenzhang** [iRASPA/RASPA2#1]
what is the mixrule when i use FEYNMAN HIBBS LENNARD JONES to calculate E/P?
The manual says :Jorgensen or Lorentz-Berthelot  only used for Lennard-Jones

**Comment by dubbelda** [comment]
The Feyman-Hibbs model is a model for hydrogen to take QM effects into account.
There is no unique mixing rule, as it is developed for pure hydrogen.
