### ISSUE TITLE
memory leaks?

### ISSUE THREAD

**Issue by ltalirz** [iRASPA/RASPA2#11]
I just ran [cppcheck](http://cppcheck.sourceforge.net/) over the code.

While most notes are about uninitialized variables (maybe good to fix, but not necessarily relevant), it also came up with two memory leaks that are probably good to investigate/close:

```
src/minimization.c:5443:1: error: Memory leak: Gradient [memleak]
}
^
src/minimization.c:5443:1: error: Memory leak: EigenValues [memleak]
}
^
```

Furthermore there were a couple of those:
```
src/ewald.c:471:3: error: Common realloc mistake: 'Positions' nulled but not freed upon failure [memleakOnRealloc]
  Positions=(VECTOR*)realloc(Positions,MaxNumberOfCoulombicSites*sizeof(VECTOR));
  ^
```

Full output: [cpp-check.txt](https://github.com/iRASPA/RASPA2/files/5719412/cpp-check.txt)

**Comment by dubbelda** [comment]
Thanks, fixed in v2.0.41.
