### ISSUE TITLE
Problem in declaring RASPA_DIR

### ISSUE THREAD

**Issue by pzarabadip** [iRASPA/RASPA2#2]
RASPA v2.0.37 
I recently came up with a weird situation while trying to run calculations in our HPC center. I was declaring the shared directory as:
```
export RASPA_DIR=path/to/shared/library
```
Even though the path was exported and available as environmental variable but RASPA could not use it within the calculation. Instead, RASPA was looking for shared files in the directory of:
```
RASPA_DIR=$HOME/RASPA/simulations
```
We tried different cases to solve the issue.
1) This solution does not work:
```
export RASPA_DIR=path/to/shared
unset RASPA2_DIR
```
2) This solution interestingly works:
```
export RASPA2_DIR=path/to/shared
```

Based on the source code:
https://github.com/iRASPA/RASPA2/blob/4467e14c375c2e02f3839ffc63c14edf0bbde0a2/src/main.c#L57-L66
There should not be any issue but I do not know for what is the reason that RASPA is not able to read shared folder if it is declared as RASPA_DIR but it works perfectly when it is declared as RASPA2_DIR.

**Comment by dubbelda** [comment]
No other problems have been reported, closing the issue.
