### ISSUE TITLE
Issue with Ethene adsorption calculations in MOF

### ISSUE THREAD

**Issue by Sridhar-hub** [iRASPA/RASPA2#23]
Hi,

I have been doing ethene adsorption calculations in MOFs. The adsorption amount and heat of adsorption values were not matching with the experimental values. The results are very low (almost 10 times) compared to experiments. To check the forcefield of the framework and guest, i have applied different guests in the framework. I got the results close to the literature, unlike ethene. I guess something is not correct with ethene. What are the files I should look after in case the guest molecule causing an issue? 
I have attached the force_field.def and simulation.input files. Please let me know what could be the possible reason?

Thank you.
[ethene in ZIF-8.zip](https://github.com/iRASPA/RASPA2/files/6419878/ethene.in.ZIF-8.zip)

**Comment by dubbelda** [comment]
Check the force field and molecule-file and search for force fields in the literature that you can use, or otherwise develop new parameters based on reproducing the available experimental data.
