### ISSUE TITLE
Installation Issue

### ISSUE THREAD

**Issue by Xiaoyi-ZHANG23** [iRASPA/RASPA2#53]
Hi, I was trying to install the latest RASPA2 but it refuses to compile with some linker problem with the errors like below:
`/bin/sh ../libtool  --tag=CC   --mode=link gcc  -Wall -O3 -mfpmath=sse -fomit-frame-pointer -ftree-vectorize -fno-stack-check -funroll-loops -ffast-math   -o simulate main.o libraspa2.la 
libtool: link: gcc -Wall -O3 -mfpmath=sse -fomit-frame-pointer -ftree-vectorize -fno-stack-check -funroll-loops -ffast-math -o .libs/simulate main.o  ./.libs/libraspa2.so -lm -Wl,-rpath -Wl,/home/ekn8665/RASPA/simulations/lib
./.libs/libraspa2.so: undefined reference to `HybridNVEAlchDrift'`
Wondering how to get it fixed.
Thanks!

**Comment by shabnam8920** [comment]
Hi,
this is my problem, as well. help me, please.
Thanks!

**Comment by Xiaoyi-ZHANG23** [comment]
The problem is almost fixed now with the new update. The only problem is that with Quest, it does not support C99 mode, so need to add "-std=c99" to CFLAGS in make file, just to make a note

**Comment by Xiaoyi-ZHANG23** [comment]
update: For QUEST only, when configure, configure using your directory for raspa2, and load  gcc/12.3.0-gcc-10.4.0 for make
