### ISSUE TITLE
Installation

### ISSUE THREAD

**Issue by sli259** [iRASPA/RASPA2#7]
I am trying to install the package locally follow the instruction here, but couldn't find any of these files. 
• rm -rf autom4te.cache
• mkdir m4
• aclocal
• autoreconf -i
• automake --add-missing
• autoconf
• ./configure --prefix=${RASPA_DIR}
There is also no configure file in any directory. Am I doing it right?

**Comment by assoua** [comment]
if it is for the installation I try the following step form:
$ sudo apt install build-essential git autoconf automake libtool make
$ git clone https://github.com/numat/RASPA2
$ mkdir -vp Research/simulations
$ cd RASPA2/
$ export RASPA DIR=${HOME}/Research/simulations/
$ mkdir m4
$ aclocal
$ autoreconf -i
$ automake --add-missing
$ autoconf
$ ./configure --prefix=${RASPA_DIR}
$ make
$ sudo make install following step:

**Comment by sli259** [comment]
Thank you so much!

**Comment by simsow** [comment]
I'm trying to install Raspa, I could not find how to start with the code, which application I have to use to start the installation code in windows.
It will so kind of you to indicate to me the correct way to install Raspa.

**Comment by sli259** [comment]
@simsow 
I am not sure how it works out on Windows. I used the same steps as shown above to install it on Linux and it worked fine.

**Comment by simsow** [comment]
what program should i start the code with in linux, should i keep this mark: $ in the code
thank you so much for the help

**Comment by sli259** [comment]
@simsow 
Use the terminal to type in the command. Which installation are you following?

**Comment by simsow** [comment]
Thank you so much I successfully installed Raspa following the same code below.
I am not able to run the software

**Comment by sli259** [comment]
@simsow 
You need to be more specific about the issue, like what have you run and what was the output.
