### ISSUE TITLE
Python interface `RASPA2.run()` fails for `v2.0.38`

### ISSUE THREAD

**Issue by neumannrf** [iRASPA/RASPA2#9]
In a Fedora 32 machine, I executed the commands below to install `RASPA2` version 2.0.38.
```Shell
$ dnf install -y automake blas-devel diffutils fftw-devel file gcc-c++ lapack-devel libtool make python3-devel which
$ pip install .
```

Then I ran
```Shell
$ python3 -c "import RASPA2; RASPA2.run('Cu-BTC', 'CO2')"
```
and got
```Shell
$ ERROR in cif-file: no proper space group definition found
```

Yet, when I run `simulation simulation.input` by passing [this input file](https://github.com/iRASPA/RASPA2/blob/master/examples/Basic/Adsorption_of_CO2_in_CU-BTC/simulation.input) that uses the same Cu-BTC framework CIF file, the simulation works fine.

**Comment by dubbelda** [comment]
The python-part is added by 'numat' (https://github.com/numat/RASPA2).
